name: Build and Push image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io
          
      - name: Build_main :latest
        run: docker build -f ./main/Dockerfile -t rint3579/dockertest_main:latest .
        
      - name: Build_dev :latest
        run: docker build -f ./dev/Dockerfile -t rint3579/dockertest_dev:latest .
        
      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push rint3579/imagename:latest
